{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","driverError":{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","file":"nbtinsert.c","length":198,"line":"656","name":"error","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","table":"user"},"file":"nbtinsert.c","length":198,"level":"error","line":"656","message":"duplicate key value violates unique constraint \"user_username_key\" duplicate key value violates unique constraint \"user_username_key\"","parameters":["gdo","c58f257617be7e34c4d731f6c4f3dfeb05a8257d3063a77f873d3668763abc7d.b37be9c7242a1b9e",202,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"user_username_key\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","driverError":{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","file":"nbtinsert.c","length":198,"line":"656","name":"error","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","table":"user"},"file":"nbtinsert.c","length":198,"level":"error","line":"656","message":"duplicate key value violates unique constraint \"user_username_key\" duplicate key value violates unique constraint \"user_username_key\"","parameters":["gdo","407ae74127c1dae650570fefe240d786642d3ca59b63d1d581af1211b072209b.ca112fa20e53d633",203,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"user_username_key\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","driverError":{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","file":"nbtinsert.c","length":198,"line":"656","name":"error","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","table":"user"},"file":"nbtinsert.c","length":198,"level":"error","line":"656","message":"duplicate key value violates unique constraint \"user_username_key\" duplicate key value violates unique constraint \"user_username_key\"","parameters":["gdo","b75568e67fcc8438066ba994a9f3e9cf08e4732b3aa54a071dc386040444682d.c32f206ad8b9601c",204,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"user_username_key\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","driverError":{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","file":"nbtinsert.c","length":198,"line":"656","name":"error","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","table":"user"},"file":"nbtinsert.c","length":198,"level":"error","line":"656","message":"duplicate key value violates unique constraint \"user_username_key\" duplicate key value violates unique constraint \"user_username_key\"","parameters":["gdo","2aae5420de364cecbfaa4a9276207b86071212de3b64fc5648d545bd2a257842.be6e6f762a50c02f",205,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"user_username_key\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","driverError":{"code":"23505","constraint":"user_username_key","detail":"Key (username)=(gdo) already exists.","file":"nbtinsert.c","length":198,"line":"656","name":"error","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","table":"user"},"file":"nbtinsert.c","length":198,"level":"error","line":"656","message":"duplicate key value violates unique constraint \"user_username_key\" duplicate key value violates unique constraint \"user_username_key\"","parameters":["gdo","0c6b3d53d7d4b27130f24d400e9dd6f27debefe8a2cd3b73d68990b6d97a3dc4.7c78876a83b1e08b",206,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"_bt_check_unique","schema":"sec","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"user_username_key\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"level":"error","message":"Cannot create property 'Symbol(level)' on string 'duplicate key value violates unique constraint \"user_username_key\"'"}
{"level":"error","message":"Cannot create property 'Symbol(level)' on string 'duplicate key value violates unique constraint \"user_username_key\"'"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"main\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No metadata for \"Session\" was found."}
{"level":"error","message":"No metadata for \"Session\" was found."}
{"level":"error","message":"No metadata for \"Session\" was found."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"secret option required for sessions"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No metadata for \"Session\" was found."}
{"level":"error","message":"No metadata for \"Session\" was found."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"code":"42P01","driverError":{"code":"42P01","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","length":171,"line":"1159","name":"error","position":"13","routine":"parserOpenTable","severity":"ERROR"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","length":171,"level":"error","line":"1159","message":"relation \"org.calendar\" does not exist relation \"org.calendar\" does not exist","parameters":["gdo"],"position":"13","query":"INSERT INTO \"org\".\"calendar\"(\"name\", \"location_id\", \"org_id\") VALUES ($1, DEFAULT, DEFAULT) RETURNING \"id\"","routine":"parserOpenTable","severity":"ERROR","stack":"QueryFailedError: relation \"org.calendar\" does not exist\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"column \"mapping\" contains null values"}
{"level":"error","message":"constraint \"PK_f55da76ac1c3ac420f444d2ff11\" of relation \"session\" does not exist"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"constraint \"PK_f55da76ac1c3ac420f444d2ff11\" of relation \"session\" does not exist"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Failed to send confirmation email"}
{"level":"error","message":"Failed to send confirmation email"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"Failed to send confirmation email"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:161:23)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:163:53)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (/Users/gdo/Documents/Code/checkin/nestjs/src/models/main/email/email.repository.ts:14:8)\n    at MailService.sendUserConfirmation (/Users/gdo/Documents/Code/checkin/nestjs/src/common/modules/mail/mail.service.ts:24:54)\n    at AuthService.signup (/Users/gdo/Documents/Code/checkin/nestjs/src/api/auth/auth.service.ts:160:22)"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:161:23)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:163:53)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:314:14)\n    at EmailRepository.getSingupEmail (/Users/gdo/Documents/Code/checkin/nestjs/src/models/main/email/email.repository.ts:15:8)\n    at MailService.sendUserConfirmation (/Users/gdo/Documents/Code/checkin/nestjs/src/common/modules/mail/mail.service.ts:24:54)\n    at AuthService.signup (/Users/gdo/Documents/Code/checkin/nestjs/src/api/auth/auth.service.ts:160:22)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"code":"EAUTH","command":"AUTH XOAUTH2","errno":-3008,"hostname":"accounts.google.com","level":"error","message":"Failed to send confirmation email getaddrinfo ENOTFOUND accounts.google.com","sourceUrl":"https://accounts.google.com/o/oauth2/token","stack":"Error: getaddrinfo ENOTFOUND accounts.google.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","syscall":"getaddrinfo","type":"FETCH"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"level":"error","message":"request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com"}
{"code":"42703","driverError":{"code":"42703","file":"parse_relation.c","length":107,"line":"3513","name":"error","position":"8","routine":"errorMissingColumn","severity":"ERROR"},"file":"parse_relation.c","length":107,"level":"error","line":"3513","message":"Failed to send confirmation email column \"email_id\" does not exist","parameters":["signup"],"position":"8","query":"SELECT email_id, email_type_type FROM \"org\".\"email\" \"email\" LEFT JOIN \"dbo\".\"email_type\" \"email_type\" ON \"email\".\"email_type_id\" = \"email_type\".\"id\"  LEFT JOIN \"dbo\".\"recipient\" \"recipient\" ON \"email_type\".\"recipient_id\" = \"recipient\".\"id\" WHERE \"email_type\".\"name\" = $1","routine":"errorMissingColumn","severity":"ERROR","stack":"QueryFailedError: column \"email_id\" does not exist\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:161:23)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:163:53)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (/Users/gdo/Documents/Code/checkin/nestjs/src/models/main/email/email.repository.ts:11:8)\n    at MailService.sendUserConfirmation (/Users/gdo/Documents/Code/checkin/nestjs/src/common/modules/mail/mail.service.ts:23:54)\n    at AuthService.signup (/Users/gdo/Documents/Code/checkin/nestjs/src/api/auth/auth.service.ts:160:22)"}
{"code":"42883","driverError":{"code":"42883","file":"parse_oper.c","hint":"No operator matches the given name and argument types. You might need to add explicit type casts.","length":210,"line":"731","name":"error","position":"985","routine":"op_error","severity":"ERROR"},"file":"parse_oper.c","hint":"No operator matches the given name and argument types. You might need to add explicit type casts.","length":210,"level":"error","line":"731","message":"Failed to send confirmation email operator does not exist: integer = dbo.email_type","parameters":[],"position":"985","query":"SELECT \"email\".\"id\" AS \"email_id\", \"email\".\"name\" AS \"email_name\", \"email\".\"subject\" AS \"email_subject\", \"email\".\"body\" AS \"email_body\", \"email\".\"is_active\" AS \"email_is_active\", \"email\".\"org_id\" AS \"email_org_id\", \"email\".\"created_by\" AS \"email_created_by\", \"email\".\"updated_by\" AS \"email_updated_by\", \"email\".\"created_at\" AS \"email_created_at\", \"email\".\"updated_at\" AS \"email_updated_at\", \"email\".\"email_type_id\" AS \"email_email_type_id\", \"email_type\".\"id\" AS \"email_type_id\", \"email_type\".\"name\" AS \"email_type_name\", \"email_type\".\"type\" AS \"email_type_type\", \"email_type\".\"created_by\" AS \"email_type_created_by\", \"email_type\".\"updated_by\" AS \"email_type_updated_by\", \"email_type\".\"created_at\" AS \"email_type_created_at\", \"email_type\".\"updated_at\" AS \"email_type_updated_at\", \"email_type\".\"module_id\" AS \"email_type_module_id\", \"email_type\".\"recipient_id\" AS \"email_type_recipient_id\" FROM \"org\".\"email\" \"email\" LEFT JOIN \"dbo\".\"email_type\" \"email_type\" ON \"email\".\"email_type_id\" = email_type","routine":"op_error","severity":"ERROR","stack":"QueryFailedError: operator does not exist: integer = dbo.email_type\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:161:23)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:163:53)\n    at JoinAttribute.get (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (/Users/gdo/Documents/Code/checkin/nestjs/src/query-builder/SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (/Users/gdo/Documents/Code/checkin/nestjs/src/models/main/email/email.repository.ts:11:8)\n    at MailService.sendUserConfirmation (/Users/gdo/Documents/Code/checkin/nestjs/src/common/modules/mail/mail.service.ts:23:54)\n    at AuthService.signup (/Users/gdo/Documents/Code/checkin/nestjs/src/api/auth/auth.service.ts:160:22)"}
{"level":"error","message":"Error: listen EADDRINUSE: address already in use :::5000"}
{"level":"error","message":"Error: listen EADDRINUSE: address already in use :::5000"}
{"code":"42703","driverError":{"code":"42703","file":"parse_relation.c","length":109,"line":"3513","name":"error","position":"526","routine":"errorMissingColumn","severity":"ERROR"},"file":"parse_relation.c","length":109,"level":"error","line":"3513","message":"Failed to send confirmation email column email.type does not exist","parameters":[],"position":"526","query":"SELECT \"email\".\"id\" AS \"email_id\", \"email_type\".\"id\" AS \"email_type_id\", \"email_type\".\"name\" AS \"email_type_name\", \"email_type\".\"type\" AS \"email_type_type\", \"email_type\".\"created_by\" AS \"email_type_created_by\", \"email_type\".\"updated_by\" AS \"email_type_updated_by\", \"email_type\".\"created_at\" AS \"email_type_created_at\", \"email_type\".\"updated_at\" AS \"email_type_updated_at\", \"email_type\".\"module_id\" AS \"email_type_module_id\", \"email_type\".\"recipient_id\" AS \"email_type_recipient_id\", \"email_type\".\"type\" AS \"email_type_type\", email.type, \"email_type\".\"type\" FROM \"org\".\"email\" \"email\" LEFT JOIN \"dbo\".\"email_type\" \"email_type\" ON \"email\".\"email_type_id\" = \"email_type\".\"id\"","routine":"errorMissingColumn","severity":"ERROR","stack":"QueryFailedError: column email.type does not exist\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"code":"EDNS","command":"CONN","hostname":"smtp.ethereal.email","level":"error","message":"Failed to send confirmation email queryA ETIMEOUT smtp.ethereal.email","stack":"Error: queryA ETIMEOUT smtp.ethereal.email\n    at QueryReqWrap.onresolve [as oncomplete] (node:dns:213:19)","syscall":"queryA"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (2)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (3)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (4)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (5)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (6)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (7)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (8)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (9)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"code":"23502","column":"phone_number","detail":"Failing row contains (1, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:40:28.090718, 2021-11-28 13:40:28.090718, null).","driverError":{"code":"23502","column":"phone_number","detail":"Failing row contains (1, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:40:28.090718, 2021-11-28 13:40:28.090718, null).","file":"execMain.c","length":319,"line":"1965","name":"error","routine":"ExecConstraints","schema":"org","severity":"ERROR","table":"contact"},"file":"execMain.c","length":319,"level":"error","line":"1965","message":"null value in column \"phone_number\" of relation \"contact\" violates not-null constraint null value in column \"phone_number\" of relation \"contact\" violates not-null constraint","parameters":["giang","do","giangd@gmail.com"],"query":"INSERT INTO \"org\".\"contact\"(\"first_name\", \"last_name\", \"email_address\", \"street_address\", \"city\", \"postal_code\", \"phone_number\", \"created_at\", \"updated_at\", \"territory_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING \"id\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"org","severity":"ERROR","stack":"QueryFailedError: null value in column \"phone_number\" of relation \"contact\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"contact"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (2)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (3)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (4)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (5)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (6)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (7)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (8)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (9)..."}
{"code":"23502","column":"phone_number","detail":"Failing row contains (2, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:46:15.841525, 2021-11-28 13:46:15.841525, null).","driverError":{"code":"23502","column":"phone_number","detail":"Failing row contains (2, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:46:15.841525, 2021-11-28 13:46:15.841525, null).","file":"execMain.c","length":319,"line":"1965","name":"error","routine":"ExecConstraints","schema":"org","severity":"ERROR","table":"contact"},"file":"execMain.c","length":319,"level":"error","line":"1965","message":"null value in column \"phone_number\" of relation \"contact\" violates not-null constraint null value in column \"phone_number\" of relation \"contact\" violates not-null constraint","parameters":["giang","do","giangd@gmail.com"],"query":"INSERT INTO \"org\".\"contact\"(\"first_name\", \"last_name\", \"email_address\", \"street_address\", \"city\", \"postal_code\", \"phone_number\", \"created_at\", \"updated_at\", \"territory_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING \"id\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"org","severity":"ERROR","stack":"QueryFailedError: null value in column \"phone_number\" of relation \"contact\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"contact"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (2)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (3)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (4)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (5)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (6)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (7)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (8)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (9)..."}
{"code":"23502","column":"phone_number","detail":"Failing row contains (3, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:50:08.370299, 2021-11-28 13:50:08.370299, null).","driverError":{"code":"23502","column":"phone_number","detail":"Failing row contains (3, giang, do, giangd@gmail.com, null, null, null, null, 2021-11-28 13:50:08.370299, 2021-11-28 13:50:08.370299, null).","file":"execMain.c","length":319,"line":"1965","name":"error","routine":"ExecConstraints","schema":"org","severity":"ERROR","table":"contact"},"file":"execMain.c","length":319,"level":"error","line":"1965","message":"null value in column \"phone_number\" of relation \"contact\" violates not-null constraint null value in column \"phone_number\" of relation \"contact\" violates not-null constraint","parameters":["giang","do","giangd@gmail.com"],"query":"INSERT INTO \"org\".\"contact\"(\"first_name\", \"last_name\", \"email_address\", \"street_address\", \"city\", \"postal_code\", \"phone_number\", \"created_at\", \"updated_at\", \"territory_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING \"id\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"org","severity":"ERROR","stack":"QueryFailedError: null value in column \"phone_number\" of relation \"contact\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"contact"}
{"code":"23502","column":"passcode","detail":"Failing row contains (1, gdo, 9a4b83b6ba49c7dd402d4d54c3525b02e0253b5cdd5b53748c8889ef5194ee66..., null, f, f, null, null, postgres, null, 2021-11-28 13:52:08.673916, 2021-11-28 13:52:08.673916, 4, 2).","driverError":{"code":"23502","column":"passcode","detail":"Failing row contains (1, gdo, 9a4b83b6ba49c7dd402d4d54c3525b02e0253b5cdd5b53748c8889ef5194ee66..., null, f, f, null, null, postgres, null, 2021-11-28 13:52:08.673916, 2021-11-28 13:52:08.673916, 4, 2).","file":"execMain.c","length":366,"line":"1965","name":"error","routine":"ExecConstraints","schema":"sec","severity":"ERROR","table":"user"},"file":"execMain.c","length":366,"level":"error","line":"1965","message":"null value in column \"passcode\" of relation \"user\" violates not-null constraint null value in column \"passcode\" of relation \"user\" violates not-null constraint","parameters":["gdo","9a4b83b6ba49c7dd402d4d54c3525b02e0253b5cdd5b53748c8889ef5194ee66.4ef8c84786d7e983",4,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"sec","severity":"ERROR","stack":"QueryFailedError: null value in column \"passcode\" of relation \"user\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23502","column":"form_id","detail":"Failing row contains (2, gdo, 0b18d43aa2684bdea251c0a8c34f2105e09fc777d33203826de1b445117d5ffd..., 1234, f, f, null, null, postgres, null, 2021-11-28 13:52:46.380138, 2021-11-28 13:52:46.380138, 5, 2).","driverError":{"code":"23502","column":"form_id","detail":"Failing row contains (2, gdo, 0b18d43aa2684bdea251c0a8c34f2105e09fc777d33203826de1b445117d5ffd..., 1234, f, f, null, null, postgres, null, 2021-11-28 13:52:46.380138, 2021-11-28 13:52:46.380138, 5, 2).","file":"execMain.c","length":364,"line":"1965","name":"error","routine":"ExecConstraints","schema":"sec","severity":"ERROR","table":"user"},"file":"execMain.c","length":364,"level":"error","line":"1965","message":"null value in column \"form_id\" of relation \"user\" violates not-null constraint null value in column \"form_id\" of relation \"user\" violates not-null constraint","parameters":["gdo","0b18d43aa2684bdea251c0a8c34f2105e09fc777d33203826de1b445117d5ffd.36599e475ca2e51d","1234",5,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $4, $5) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"sec","severity":"ERROR","stack":"QueryFailedError: null value in column \"form_id\" of relation \"user\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23502","column":"org_id","detail":"Failing row contains (3, gdo, 7c77d7a1b638cf284deba528058487b6196f7892f65a5bab78eb91544bce155e..., 1234, f, f, 1, null, postgres, null, 2021-11-28 13:54:41.740109, 2021-11-28 13:54:41.740109, 6, 2).","driverError":{"code":"23502","column":"org_id","detail":"Failing row contains (3, gdo, 7c77d7a1b638cf284deba528058487b6196f7892f65a5bab78eb91544bce155e..., 1234, f, f, 1, null, postgres, null, 2021-11-28 13:54:41.740109, 2021-11-28 13:54:41.740109, 6, 2).","file":"execMain.c","length":359,"line":"1965","name":"error","routine":"ExecConstraints","schema":"sec","severity":"ERROR","table":"user"},"file":"execMain.c","length":359,"level":"error","line":"1965","message":"null value in column \"org_id\" of relation \"user\" violates not-null constraint null value in column \"org_id\" of relation \"user\" violates not-null constraint","parameters":["gdo","7c77d7a1b638cf284deba528058487b6196f7892f65a5bab78eb91544bce155e.90988353200f8375","1234",1,6,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, $4, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $5, $6) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"sec","severity":"ERROR","stack":"QueryFailedError: null value in column \"org_id\" of relation \"user\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23502","column":"updated_by","detail":"Failing row contains (4, gdo, b55fa114568d97dfdd7824b1006f8f188a6ee6e0a5616aa3dd77afb22d7c291c..., 1234, f, f, 1, 1, postgres, null, 2021-11-28 14:10:29.023133, 2021-11-28 14:10:29.023133, 7, 2).","driverError":{"code":"23502","column":"updated_by","detail":"Failing row contains (4, gdo, b55fa114568d97dfdd7824b1006f8f188a6ee6e0a5616aa3dd77afb22d7c291c..., 1234, f, f, 1, 1, postgres, null, 2021-11-28 14:10:29.023133, 2021-11-28 14:10:29.023133, 7, 2).","file":"execMain.c","length":364,"line":"1965","name":"error","routine":"ExecConstraints","schema":"sec","severity":"ERROR","table":"user"},"file":"execMain.c","length":364,"level":"error","line":"1965","message":"null value in column \"updated_by\" of relation \"user\" violates not-null constraint null value in column \"updated_by\" of relation \"user\" violates not-null constraint","parameters":["gdo","b55fa114568d97dfdd7824b1006f8f188a6ee6e0a5616aa3dd77afb22d7c291c.0cf13c5190324f61","1234",1,1,7,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, $4, $5, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $6, $7) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ExecConstraints","schema":"sec","severity":"ERROR","stack":"QueryFailedError: null value in column \"updated_by\" of relation \"user\" violates not-null constraint\n    at QueryFailedError.TypeORMError [as constructor] (/Users/gdo/Documents/Code/checkin/nestjs/src/error/TypeORMError.ts:7:9)\n    at new QueryFailedError (/Users/gdo/Documents/Code/checkin/nestjs/src/error/QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (/Users/gdo/Documents/Code/checkin/nestjs/src/driver/postgres/PostgresQueryRunner.ts:247:19)\n    at step (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:124:57)\n    at rejected (/Users/gdo/Documents/Code/checkin/nestjs/node_modules/tslib/tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","driverError":{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"line":"2783","name":"error","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","table":"user"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"level":"error","line":"2783","message":"insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\" insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"","parameters":["gdo","b78744201d57d9fc4b66ad35c30d155863d6dc83d6a81a6cc6c28936eff896b7.00cc258358b68f25","1234",1,1,1,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, $3, DEFAULT, DEFAULT, $4, $5, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $6, $7) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","stack":"QueryFailedError: insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","driverError":{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"line":"2783","name":"error","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","table":"user"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"level":"error","line":"2783","message":"insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\" insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"","parameters":["gdo","66b14acc7c058fccba12064e43761a4325c623a88f82b70ee3d490331c7853df.29ad4d6ace8d6aec",1,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","stack":"QueryFailedError: insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","driverError":{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"line":"2783","name":"error","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","table":"user"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"level":"error","line":"2783","message":"insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\" insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"","parameters":["gdo","77acf46a4eb9b3a52c30de4ee204379305c1b08b71e1e5705f190c5666ab565a.b80ab4a82afe8b22",1,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","stack":"QueryFailedError: insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","driverError":{"code":"23503","constraint":"FK_fb2e442d14add3cefbdf33c4561","detail":"Key (role_id)=(2) is not present in table \"role\".","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"line":"2783","name":"error","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","table":"user"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\ri_triggers.c","length":323,"level":"error","line":"2783","message":"insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\" insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"","parameters":["gdo","4090cf09dc25357e657bd878900f78c2fe390b7ab6d4991998cf27af816871d8.47c425f80211fc80",1,2],"query":"INSERT INTO \"sec\".\"user\"(\"username\", \"password\", \"passcode\", \"is_new_password\", \"is_active\", \"form_id\", \"org_id\", \"created_by\", \"updated_by\", \"created_at\", \"updated_at\", \"contact_id\", \"role_id\") VALUES ($1, $2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $3, $4) RETURNING \"id\", \"is_new_password\", \"is_active\", \"created_by\", \"created_at\", \"updated_at\"","routine":"ri_ReportViolation","schema":"sec","severity":"ERROR","stack":"QueryFailedError: insert or update on table \"user\" violates foreign key constraint \"FK_fb2e442d14add3cefbdf33c4561\"\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","table":"user"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Unable to connect to the database. Retrying (1)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (2)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (3)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (4)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (5)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (6)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (7)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (8)..."}
{"level":"error","message":"Unable to connect to the database. Retrying (9)..."}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:161:23)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:163:53)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (C:\\CMR\\gdo\\checkin\\nestjs\\src\\models\\main\\email\\email.repository.ts:20:8)\n    at MailService.sendUserConfirmation (C:\\CMR\\gdo\\checkin\\nestjs\\src\\common\\modules\\mail\\mail.service.ts:23:54)\n    at AuthService.signup (C:\\CMR\\gdo\\checkin\\nestjs\\src\\api\\auth\\auth.service.ts:160:22)"}
{"level":"error","message":"Failed to send confirmation email Relation with property path email_type_id in entity was not found.","stack":"TypeORMError: Relation with property path email_type_id in entity was not found.\n    at new TypeORMError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at JoinAttribute.getValue (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:161:23)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:163:53)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (C:\\CMR\\gdo\\checkin\\nestjs\\src\\models\\main\\email\\email.repository.ts:20:8)\n    at MailService.sendUserConfirmation (C:\\CMR\\gdo\\checkin\\nestjs\\src\\common\\modules\\mail\\mail.service.ts:26:54)\n    at AuthService.signup (C:\\CMR\\gdo\\checkin\\nestjs\\src\\api\\auth\\auth.service.ts:160:22)"}
{"code":"42712","driverError":{"code":"42712","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","length":184,"line":"420","name":"error","routine":"checkNameSpaceConflicts","severity":"ERROR"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","length":184,"level":"error","line":"420","message":"Failed to send confirmation email table name \"email_type\" specified more than once","parameters":["signup"],"query":"SELECT \"email\".\"id\" AS \"email_id\", \"email\".\"name\" AS \"email_name\", \"email\".\"subject\" AS \"email_subject\", \"email\".\"body\" AS \"email_body\", \"email\".\"is_active\" AS \"email_is_active\", \"email\".\"org_id\" AS \"email_org_id\", \"email\".\"created_by\" AS \"email_created_by\", \"email\".\"updated_by\" AS \"email_updated_by\", \"email\".\"created_at\" AS \"email_created_at\", \"email\".\"updated_at\" AS \"email_updated_at\", \"email\".\"email_type_id\" AS \"email_email_type_id\", \"email_type\".\"id\" AS \"email_type_id\", \"email_type\".\"name\" AS \"email_type_name\", \"email_type\".\"type\" AS \"email_type_type\", \"email_type\".\"created_by\" AS \"email_type_created_by\", \"email_type\".\"updated_by\" AS \"email_type_updated_by\", \"email_type\".\"created_at\" AS \"email_type_created_at\", \"email_type\".\"updated_at\" AS \"email_type_updated_at\", \"email_type\".\"module_id\" AS \"email_type_module_id\", \"email_type\".\"recipient_id\" AS \"email_type_recipient_id\", \"recipient\".\"id\" AS \"recipient_id\", \"recipient\".\"name\" AS \"recipient_name\", \"recipient\".\"email_address\" AS \"recipient_email_address\", \"recipient\".\"created_by\" AS \"recipient_created_by\", \"recipient\".\"updated_by\" AS \"recipient_updated_by\", \"recipient\".\"created_at\" AS \"recipient_created_at\", \"recipient\".\"updated_at\" AS \"recipient_updated_at\", \"email_type\".\"id\" AS \"email_type_id\", \"email_type\".\"name\" AS \"email_type_name\", \"email_type\".\"type\" AS \"email_type_type\", \"email_type\".\"created_by\" AS \"email_type_created_by\", \"email_type\".\"updated_by\" AS \"email_type_updated_by\", \"email_type\".\"created_at\" AS \"email_type_created_at\", \"email_type\".\"updated_at\" AS \"email_type_updated_at\", \"email_type\".\"module_id\" AS \"email_type_module_id\", \"email_type\".\"recipient_id\" AS \"email_type_recipient_id\", \"recipient\".\"id\" AS \"recipient_id\", \"recipient\".\"name\" AS \"recipient_name\", \"recipient\".\"email_address\" AS \"recipient_email_address\", \"recipient\".\"created_by\" AS \"recipient_created_by\", \"recipient\".\"updated_by\" AS \"recipient_updated_by\", \"recipient\".\"created_at\" AS \"recipient_created_at\", \"recipient\".\"updated_at\" AS \"recipient_updated_at\", email_type, recipient FROM \"org\".\"email\" \"email\" LEFT JOIN \"dbo\".\"email_type\" \"email_type\" ON \"email_type\".\"id\"=\"email\".\"email_type_id\"  LEFT JOIN \"dbo\".\"recipient\" \"recipient\" ON \"recipient\".\"id\"=\"email_type\".\"recipient_id\"  LEFT JOIN \"dbo\".\"email_type\" \"email_type\" ON \"email\".\"email_type_id\" = \"email_type\".\"id\"  LEFT JOIN \"dbo\".\"recipient\" \"recipient\" ON \"email_type\".\"recipient_id\" = \"recipient\".\"id\" WHERE \"email_type\".\"name\" = $1","routine":"checkNameSpaceConflicts","severity":"ERROR","stack":"QueryFailedError: table name \"email_type\" specified more than once\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"No repository for \"Session\" was found. Looks like this entity is not registered in current \"default\" connection?"}
{"code":"42703","driverError":{"code":"42703","file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","hint":"Perhaps you meant to reference the column \"r.email_address\".","length":235,"line":"3294","name":"error","position":"65","routine":"errorMissingColumn","severity":"ERROR"},"file":"d:\\pginstaller.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_relation.c","hint":"Perhaps you meant to reference the column \"r.email_address\".","length":235,"level":"error","line":"3294","message":"Failed to send confirmation email column e.email_address does not exist","parameters":["signup"],"position":"65","query":"SELECT \"e\".\"id\" as id, \"et\".\"type\" as type, \"e\".\"name\" as name, e.email_address as emailAddress, \"e\".\"subject\" as subject, \"e\".\"body\" as body, \"e\".\"is_active\" as isActive, \"e\".\"org_id\" as orgId FROM \"org\".\"email\" \"e\" LEFT JOIN \"dbo\".\"email_type\" \"et\" ON \"e\".\"email_type_id\" = \"et\".\"id\"  LEFT JOIN \"dbo\".\"recipient\" \"r\" ON \"et\".\"recipient_id\" = \"r\".\"id\" WHERE \"et\".\"name\" = $1","routine":"errorMissingColumn","severity":"ERROR","stack":"QueryFailedError: column e.email_address does not exist\n    at QueryFailedError.TypeORMError [as constructor] (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (C:\\CMR\\gdo\\checkin\\nestjs\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (C:\\CMR\\gdo\\checkin\\nestjs\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Failed to send confirmation email \"et\" alias was not found. Maybe you forgot to join it?","stack":"TypeORMError: \"et\" alias was not found. Maybe you forgot to join it?\n    at new TypeORMError (C:\\CMR\\gdo\\checkin\\nestjs\\src\\error\\TypeORMError.ts:7:9)\n    at QueryExpressionMap.findAliasByName (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\QueryExpressionMap.ts:387:19)\n    at JoinAttribute.getValue (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:147:72)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:163:53)\n    at JoinAttribute.get (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\JoinAttribute.ts:176:18)\n    at SelectQueryBuilder.join (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:1357:27)\n    at SelectQueryBuilder.leftJoin (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:314:14)\n    at SelectQueryBuilder.leftJoinAndSelect (C:\\CMR\\gdo\\checkin\\nestjs\\src\\query-builder\\SelectQueryBuilder.ts:394:14)\n    at EmailRepository.getSingupEmail (C:\\CMR\\gdo\\checkin\\nestjs\\src\\models\\main\\email\\email.repository.ts:11:8)\n    at MailService.sendUserConfirmation (C:\\CMR\\gdo\\checkin\\nestjs\\src\\common\\modules\\mail\\mail.service.ts:26:54)"}
